### ISSUE TITLE
sendEvent doesn't support custom properties

### ISSUE THREAD

**Issue by TonnyORG** [plausible/plausible-tracker#2]
## Versions
- 0.2.2

## Describe the bug
I'm trying to use custom props in the events, the same way you do in your [cloud-hosted client](https://docs.plausible.io/custom-event-goals#using-custom-props), however it is not supported in the NPM package.

## Expected behavior
Send custom properties for the event and get them captured and displayed in the dashboard.

## Steps to reproduce

Steps:
1. Install normally
2. Assign it to a variable
```
import Plausible from 'plausible-tracker';
const tracker = Plausible({
  domain: 'mydomain.com',
  apiHost: 'https://tracker.mydomain.com'
});
```
3. I tried both, sending it in the data and in the options parameter, no one worked
```
tracker.trackEvent(event, {}, {props: {style: 'red'}})
// and
tracker.trackEvent(event, {props: {style: 'red'}})
```

## Your Environment
 - Device: Desktop
 - OS: Mac
 - Browser: Chrome
 - Version: 86.0.4240.183

## Additional context
I would like to know if this package has fewer options or if is it "outdated" compared to your cloud-hosted JS client. The point for me of using this package is to integrate the JS client in my `app.js` application so I don't have to rely on loading external scripts. It would be great that this package is up-to-date with what you actually run on your cloud client (a.k.a.: https://plausible.io/js/plausible.js)

**Comment by Maronato** [comment]
You are correct, it was outdated, but now with [v0.3.0](https://github.com/plausible/plausible-tracker/blob/master/CHANGELOG.md#030-2020-11-08) it should support custom props on events. Please give it a try and let me know if it works correctly :)

**Comment by TonnyORG** [comment]
> You are correct, it was outdated, but now with [v0.3.0](https://github.com/plausible/plausible-tracker/blob/master/CHANGELOG.md#030-2020-11-08) it should support custom props on events. Please give it a try and let me know if it works correctly :)

It works now, tyvm for the quick response taken!
