### ISSUE TITLE
Feature Request: User management at the root/global level

### ISSUE THREAD

**Issue by MatBenfield** [plausible/plausible-tracker#30]
## Detailed Description
We have a number of websites being tracked and each website has its own people menu and access control. It is quite tiresome to go through each of these to remove a colleague who has left the organisation

## Context
Some global user management would make access control more easily managed, this would benefit anyone with more than a few websites.

## Possible Implementation
If you have a list of websites and a list of users, one should be able to create a list of sites that the user exists for and from that user view be able to remove sites - until non-remain and the user can be deleted.

**Comment by metmarkosaric** [comment]
thanks for your feedback @MatBenfield! the place for any enhancements and features requests is our discussion forum where we have all of the ideas listed. there's already a thread for this specific idea there so please add your comments there instead. see https://github.com/plausible/analytics/discussions/1350. thanks!
