### ISSUE TITLE
The npm package of v0.3.6 has no "build" directory

### ISSUE THREAD

**Issue by ouuan** [plausible/plausible-tracker#34]
## Versions

- 0.3.6

## Describe the bug

The npm package of v0.3.6 has no "build" directory.

## Expected behavior

There should be `build/module/index.js`.

## Steps to reproduce

Install plausible-tracker@0.3.5 via npm.

## Your Environment

 - OS: Arch Linux

**Comment by ukutaht** [comment]
Released v0.3.7 with a fix
