### ISSUE TITLE
0.3.7 breaks nuxt.js because of localStorage check

### ISSUE THREAD

**Issue by mschoeffmann** [plausible/plausible-tracker#35]
## Versions
- 0.3.7

## Describe the bug
When upgrading the dependencies with `npm update`, the `plausible-tracker` module gets updated from 0.3.5 to 0.3.7.

After the update `nuxt dev` starts without issues, but opening a page results in infinite loading without any error message in the console or browser. Disabling plausible fixes the issue.

Disabling the line `const canAccessLocalStorage = typeof window.localStorage?.getItem === 'function';` at `node_modules/plausible-tracker/build/module/lib/request.js:13` allows nuxt to work properly again.

## Your Environment
 - Device: MacBookPro 16 (intel)
 - OS: macOS 12.4
 - Browser: Chrome (v102) and Safari (v15.5)

**Comment by ukutaht** [comment]
Thanks for reporting.

I've released 0.3.8 which uses a different pattern to access localStorage. Could you give it a try? Thanks

**Comment by mschoeffmann** [comment]
Confirmed - it's working in 0.3.8
Thank you!
