### ISSUE TITLE
hashMode:false is ignored in dashboard

### ISSUE THREAD

**Issue by k9ordon** [plausible/plausible-tracker#42]
## Versions

- 0.3.8
- plausible cloud

## Describe the bug

Setting `hashMode:false` in the tracker options does not disable hash mode in plausible analytics.
I still get hrefs containing "#" in the dashboard.

## Expected behavior

`hashMode:false` discards the hash part of the URL in the plausible dashboard.

## Steps to reproduce

Steps:
1. setup plausible-tracker
2. create a `<a href="#1">1</a>`
3. click the link
4. `/#1` shows up in the dashboard

## Your Environment

 - Device: macbook
 - OS: osx
 - Browser: chrome
 - Version: 102

## Additional context

The disabled hash param is sending a zero int value ([Tracker Code](https://github.com/plausible/plausible-tracker/blob/294405cafc934ee666c1a295a5b2fd8737993ce2/src/lib/request.ts#L67)). The analytics controller seems to handle this as `true` ([Analytics Code](https://github.com/plausible/analytics/blob/b415ebe77674494e1bc03e7d5bf6eca12eddbb8b/lib/plausible_web/controllers/api/external_controller.ex#L276)). 

I also tried this with script based tracking. Adding `.hash` the the script results in adding a `h:1` param to the request. Without `.hash` the `h`-param is omitted (not set to `0` as in the tracker-version) and is working with the serverside condition.

**Comment by RobertJoonas** [comment]
Hi @k9ordon!

This change would make it work indeed. But I think it's intuitive, that `0` should represent a `false` value in this case. I've made a change in how this is interpreted in the Elixir app (see: https://github.com/plausible/analytics/pull/2082). So I don't think we need to merge this PR.

Sorry for the inconvenience!

**Comment by k9ordon** [comment]
Looks good 👍
