### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by HenkVanMaanen** [plausible/plausible-tracker#53]
Is this repo still maintained? I ask this because the tracker in the main repo is newer than this one.

See: https://github.com/plausible/analytics/tree/master/tracker

**Comment by Daniel15** [comment]
It's strange... You'd think both trackers would be built from the same repo given the overlap in functionality.

**Comment by HenkVanMaanen** [comment]
It's still maintained, just behind in changes

See: https://github.com/plausible/analytics/issues/3419
