### ISSUE TITLE
Install CI apps

### ISSUE THREAD

**Issue by Maronato** [plausible/plausible-tracker#6]
## Detailed Description

I'd like to have CI installed on this repo so PRs can be automatically checked for bugs, etc, but I lack the permissions to install them. 

@metmarkosaric @ukutaht what do you think? Could you install [travis](https://travis-ci.org/) and [codecov](https://codecov.io/) here?

**Comment by ukutaht** [comment]
Sure, happy to help. Let's see if this works, do let me know if you need any config changes or anything

https://travis-ci.com/github/plausible/plausible-tracker
https://codecov.io/gh/plausible/plausible-tracker

**Comment by Windvis** [comment]
It seems Travis doesn't run yet when a PR is created or updated? #15 contained changes which made the tests fail but it wasn't noticed because the tests didn't run (until it was merged into the main branch).
