### ISSUE TITLE
Exception when Plausible is slow to respond

### ISSUE THREAD

**Issue by dommitchell** [plausible/plausible-tracker#63]
## Versions

- 0.1

## Describe the bug

https://plausible.io/doaj.org

First detected via one of our internals alerts at 0100h on Sunday 10th Dec 20243 (internal: a 500 response from our OAI-PMH monitor). 

We were getting a `RuntimeError: can't start new thread` exception from `doaj-public-app-1` from the Plausible logger, which has only started occurring in the last few days. See error in Kibana:

<img width="1447" alt="doaj-download" src="https://github.com/plausible/plausible-tracker/assets/5955396/a9c3d57d-b0fe-4310-b5c1-32480377ded2">

The pattern here is that the exception seems to occur (increasingly in frequency) each night after 0000h, and is usually sorted by the morning. This is currently the most frequent error in our monitoring, and we'll be missing events during that period.

Does Plausible take longer to respond during that period overnight, resulting in a backlog of threads to send events?

Confirmed today that this is still happening regularly every 24 hours.

![image (1)](https://github.com/plausible/plausible-tracker/assets/5955396/060abc76-84c9-4fb3-8e9b-4005a11b2cba)

## Expected behaviour

We expect to see no exception raised.

## Steps to reproduce
N/A

## Your Environment
N/A

**Comment by dommitchell** [comment]
At our end, to fix the unhandled exception, we released a hotfix to log when the exception occurs, so we don't get a 500 from the site for the sake of analytics.

**Comment by cnkk** [comment]
Hi @dommitchell!

Unfortunately the first screenshot you posted won't load.

Are we talking about our [Tracking Script](https://plausible.io/js/script.js) or [Events API](https://plausible.io/docs/events-api).
Also, the error message you posted looks like a Python error, are you sure it's related to this repo?


Anyway, I haven't seen any problems on our end with the problem you describe happening around midnight.

**Comment by dommitchell** [comment]
Hi @cnkk I swapped out the image so hopefully you can see that now. This is for the Events API. That error message is generated by our system and I got it from our developer. I'm going to call in https://github.com/Steven-Eardley and hope that he can help here. I am sure I've introduced confusion by relaying the message. Steve?

**Comment by Steven-Eardley** [comment]
That's right, we're logging to the events API - spinning off threads to register our own API hits etc. The error `can't start new thread` occurs because the request latency to Plausible increases at around 0000h, and recovers during the day.

We presume this is a performance issue at Plausible's end because we are sending requests at a sustained rate, but at certain times of day the response is slow.

**Comment by cnkk** [comment]
As far as I can see your problem is not related to the code in this repository.

Could you please contact us via mail hello@plausible.io
